### ISSUE TITLE
Does Broadcast extension work, somehow can not set it up?

### ISSUE THREAD

**Issue by dmyma** [ciscospark/spark-ios-sdk-example#20]

**Comment by Noble-Six** [comment]
Hi @dmyma, Did you set your own App Group ID in this Demo App?
It used default App Group ID created by our own Apple developer certificate.
you can follow this guide https://github.com/webex/spark-ios-sdk/wiki/Set-up-an-App-Group to get this.
And change the code in VideoCallViewController.swift
```swift
MediaOption.audioVideoScreenShare(video: (self.self.selfView!, self.remoteView!), screenShare: nil, applicationGroupIdentifier: "YOUR APP GROUP ID HERE")
```
And Extension SampleHandler.swift
```swift
SparkBroadcastExtension.sharedInstance.start(applicationGroupIdentifier: "YOUR APP GROUP ID HERE") {
    ...
}
```
If it doesn't work for you. Please comments here. Thank you.

**Comment by dmyma** [comment]
Thank you for your reply, it is working now. Sometime I can not get the incoming call, but that is another issue. We can close this ticket.

**Comment by Noble-Six** [comment]
Hi @dmyma, for the KitchenSink it focuses on how to call and use APIs. It's not good enough for the calling&meeting logic for the end user.
We have another Demo [Buddies](https://github.com/webex/spark-ios-sdk-example-buddies) which we develop it as a real-time communication(call and messaging) applications. You can try this, it could handle calling logic in the right way.
If you still meet the incoming call issue, please create an issue in our repo and let us help you.
