### ISSUE TITLE
If two users call each other, they don't usually receive video and can't accept future incoming calls

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk-example#3]
If two users enter the Initiate Call screen and call each other, the app enters a state where they are able to hear each other's audio, but video is usually hidden for the first caller and always hidden for the second caller.

The video is streaming, but it's hidden behind the tundra image for "initiated" or "ringing" calls. You can see that by turning the iPad a few times and watching just beneath the tundra image. You'll see live video for a split-second.

More importantly, if either goes to the incoming call screen, they'll never see the answer modal pop up. The only way we've found to fix this is to close and relaunch the app.

The root cause appears to be that creating a new call keeps some information from old calls, including the call URL.

We suggest that calling someone who's calling you puts you both into a normal connected state.

This may resolve itself with future improvements to the call state machine on the server.

**Comment by kliu** [comment]
Fixed in v1.2
