### ISSUE TITLE
Initiating a call before device is registered crashes the app

### ISSUE THREAD

**Issue by asynchrony-ringo** [ciscospark/spark-ios-sdk-example#4]
If the user tries to start a call via the Dial Address tab on the Initiate Call screen immediately after logging in (before they register their device), the app hard-crashes. Immediately usually means in less than a second.

The crash is due to the force unwrap in the CallManager.createOutgoingCall() method.
To replicate: delay the completion of the registration. Ensure the device is not already registered. Add code to ResponseSerialization.

```
if let url = self.request?.url, url.absoluteString.contains("devices/ios") {
    print("delaying call to \(url.absoluteString)")
    Thread.sleep(forTimeInterval: 15)
}
```

**Comment by kliu** [comment]
Fixed in v1.2
